// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

namespace WebApplication1.Migrations
{
    [DbContext(typeof(EntityContext))]
    [Migration("20191209103904_addedUserRestaurant")]
    partial class addedUserRestaurant
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication1.Models.Badge", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Badge");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ImageURL = "#",
                            Name = "Vegetarmærket"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Image", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.Property<string>("URL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Image");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            RestaurantId = 1,
                            URL = "#"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.KitchenType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("KitchenType");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Dansk"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Menu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RestaurantName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Menu");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            RestaurantName = "Café Smagløs"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.MenuItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Categories")
                        .HasColumnType("int");

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(4,2)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("MenuId");

                    b.ToTable("MenuItem");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Categories = 0,
                            MenuId = 1,
                            Price = 50.99m,
                            Title = "Stegt flæsk med persillesovs"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Priceclass", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PriceclassValue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Priceclass");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            PriceclassValue = "$"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Restaurant", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phonenumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priceclass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Zipcode")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Restaurant");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Address = "Klostertorvet 7",
                            Description = "Cafe Smagløs Aarhus C er en café med alt det, man forventer en cafe har. Brunch, burger, sandwich m.m. Der er tilmed en hyggelig stemning såvel ude som inde. Af og til har de bands til at komme og spille, så aftenen bliver en ekstra oplevelse. Sæt dig med en drink og nyd stemningen.",
                            MenuId = 1,
                            Name = "Cafe Smagløs",
                            Phonenumber = "+45 123 456 78",
                            Priceclass = "$",
                            Zipcode = 8000
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.RestaurantBadge", b =>
                {
                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.Property<int>("BadgeId")
                        .HasColumnType("int");

                    b.HasKey("RestaurantId", "BadgeId");

                    b.HasIndex("BadgeId");

                    b.ToTable("RestaurantBadge");

                    b.HasData(
                        new
                        {
                            RestaurantId = 1,
                            BadgeId = 1
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.RestaurantKitchenType", b =>
                {
                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.Property<int>("KitchenTypeId")
                        .HasColumnType("int");

                    b.HasKey("RestaurantId", "KitchenTypeId");

                    b.HasIndex("KitchenTypeId");

                    b.ToTable("RestaurantKitchenType");

                    b.HasData(
                        new
                        {
                            RestaurantId = 1,
                            KitchenTypeId = 1
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Setting", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Distance")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Setting");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Distance = 5,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.SettingKitchenType", b =>
                {
                    b.Property<int>("SettingId")
                        .HasColumnType("int");

                    b.Property<int>("KitchenTypeId")
                        .HasColumnType("int");

                    b.HasKey("SettingId", "KitchenTypeId");

                    b.HasIndex("KitchenTypeId");

                    b.ToTable("SettingKitchenType");

                    b.HasData(
                        new
                        {
                            SettingId = 1,
                            KitchenTypeId = 1
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.SettingPriceclass", b =>
                {
                    b.Property<int>("SettingId")
                        .HasColumnType("int");

                    b.Property<int>("PriceclassId")
                        .HasColumnType("int");

                    b.HasKey("SettingId", "PriceclassId");

                    b.HasIndex("PriceclassId");

                    b.ToTable("SettingPriceclass");

                    b.HasData(
                        new
                        {
                            SettingId = 1,
                            PriceclassId = 1
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Location = "Aarhus C",
                            Password = "Password",
                            Username = "Admin"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.UserRestaurant", b =>
                {
                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RestaurantId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRestaurant");

                    b.HasData(
                        new
                        {
                            RestaurantId = 1,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.MenuItem", b =>
                {
                    b.HasOne("WebApplication1.Models.Menu", null)
                        .WithMany("MenuItems")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApplication1.Models.RestaurantBadge", b =>
                {
                    b.HasOne("WebApplication1.Models.Badge", "Badge")
                        .WithMany("RestaurantBadges")
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.Restaurant", "Restaurant")
                        .WithMany("RestaurantBadges")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApplication1.Models.RestaurantKitchenType", b =>
                {
                    b.HasOne("WebApplication1.Models.KitchenType", "KitchenType")
                        .WithMany("RestaurantKitchenTypes")
                        .HasForeignKey("KitchenTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.Restaurant", "Restaurant")
                        .WithMany("RestaurantKitchenTypes")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApplication1.Models.Setting", b =>
                {
                    b.HasOne("WebApplication1.Models.User", null)
                        .WithOne("Settings")
                        .HasForeignKey("WebApplication1.Models.Setting", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApplication1.Models.SettingKitchenType", b =>
                {
                    b.HasOne("WebApplication1.Models.KitchenType", "KitchenType")
                        .WithMany("SettingKitchenTypes")
                        .HasForeignKey("KitchenTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.Setting", "Setting")
                        .WithMany("SettingKitchenTypes")
                        .HasForeignKey("SettingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApplication1.Models.SettingPriceclass", b =>
                {
                    b.HasOne("WebApplication1.Models.Priceclass", "Priceclass")
                        .WithMany("SettingPriceclasses")
                        .HasForeignKey("PriceclassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.Setting", "Setting")
                        .WithMany("SettingPriceclasses")
                        .HasForeignKey("SettingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApplication1.Models.UserRestaurant", b =>
                {
                    b.HasOne("WebApplication1.Models.Restaurant", "Restaurant")
                        .WithMany("UserRestaurants")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.User", "User")
                        .WithMany("UserRestaurants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
